version: '3'

services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade
    restart: always
    environment:
      - MEMORY="0"  # Unbegrenzter Speicher
      - CPUS="0.9"  # Nutzung von 90% einer CPU
    volumes:
      - ./user_data:/freqtrade/user_data
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: 0  # Unbegrenzter Speicher
        reservations:
          cpus: '0.9'
          memory: 0
    ports:
      - "8080:8080"
    command: >
      trade
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy
    privileged: true  # Erlaubt erweiterten Zugriff
    oom_kill_disable: true  # OOM-Killer deaktivieren
    networks:
      - freqtrade_net

networks:
  freqtrade_net:
    driver: bridge
